@hostname=localhost
@port=8082

GET http://{{hostname}}:{{port}}/stocks/quote/SMP
###

GET http://{{hostname}}:{{port}}/stocks/fullQuote/SMP

###

POST http://{{hostname}}:{{port}}/stocks/market-activity/
Content-Type: application/json

{
    "symbols" : ["SMP", "Example", "Foo", "Bar"]
}

###

PUT http://{{hostname}}:{{port}}/stocks/order
Content-Type: application/json

{
    "symbol" : "SMP",
    "quantity" : 100,
    "price" : 100.00
}