openapi: 3.0.1
info:
  title: HelloService
  version: 0.1.0
servers:
- url: "{server}:{port}/HelloService"
  variables:
    server:
      default: http://localhost
    port:
      default: port
paths:
  /greet/{name}:
    get:
      operationId: getGreetName
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /greet:
    get:
      operationId: getGreet
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components: {}
